<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey'); 
?>
<div class="return-refund">
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
	  <form class="tabset contact" action="<?= $block->escapeUrl($block->getUrl().'intenq/post/index') ?>"
			  id="contact-form"
			  method="post"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'
              enctype="multipart/form-data">
			

<input name="form_key" type="hidden" value="<?php echo $FormKey->getFormKey();?>">
			
          <div data-role="page-body">
            <fieldset class="fieldset">
              <div class="fieldset row">
                <div class="fields col-md-12">
                  <h3><?= $block->escapeHtml(__('Your Personal Details')) ?></h3>
                </div>
                <div class="fields col-md-6">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('First Name')) ?> <span>*</span></label>
                      <input name="first_name" id="first_name" placeholder="First Name" class="input-text" autocomplete="off" type="text" data-validate="{required:true}" aria-required="true" value="<?= $block->escapeHtmlAttr($this->helper(\InternationalEnquires\Form\Helper\Data::class)->getPostValue('first_name')) ?>">
                    </div>
                  </div>
                </div>
                <div class="fields col-md-6">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('Last Name')) ?> <span>*</span></label>
                      <input name="last_name" id="last_name" placeholder="Last Name" class="input-text" autocomplete="off" type="text" data-validate="{required:true}" aria-required="true" value="<?= $block->escapeHtmlAttr($this->helper(\InternationalEnquires\Form\Helper\Data::class)->getPostValue('last_name')) ?>">
                    </div>
                  </div>
                </div>
              </div>
              <div class="fieldset row">
                <div class="fields col-md-6">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('Email')) ?> <span>*</span></label>
                      <input name="email" id="email"  placeholder="email" class="input-text" autocomplete="off" type="text" data-validate="{required:true,'validate-email':true}" aria-required="true" value="<?= $block->escapeHtmlAttr($this->helper(\InternationalEnquires\Form\Helper\Data::class)->getPostValue('email')) ?>">
                    </div>
                  </div>
                </div>
                <div class="fields col-md-6">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('Phone Number')) ?> <span>*</span></label>
                      <input name="phone_no" id="phone_no" placeholder="Phone Number" class="input-text" autocomplete="off" type="text" data-validate="{required:true,'validate-number':true}" aria-required="true" value="<?= $block->escapeHtmlAttr($this->helper(\InternationalEnquires\Form\Helper\Data::class)->getPostValue('phone_no')) ?>">
                    </div>
                  </div>
                </div>
              </div>
              <div class="fieldset row">
                <div class="fields col-md-12">
                  <h3><?= $block->escapeHtml(__('Company Details')) ?></h3>
                </div>
                <div class="fields col-md-12">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('Company Name')) ?> <span>*</span></label>
                      <input name="company_name" id="company_name" placeholder="Company Name" class="input-text" autocomplete="off" type="text" data-validate="{required:true}" aria-required="true" value="<?= $block->escapeHtmlAttr($this->helper(\InternationalEnquires\Form\Helper\Data::class)->getPostValue('company_name')) ?>">
                    </div>
                  </div>
                </div>
                <div class="fields col-md-12">
                  <div class="field name required">
                    <div class="control">
                      <input name="is_business" id="is_business" class="input-text" autocomplete="off"  type="checkbox">
                      <label><?= $block->escapeHtml(__('Are you making the account for your business?')) ?><span>*</span></label>
                    </div>
                  </div>
                </div>
              </div>
              <div class="fieldset row">
                <div class="fields col-md-12">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('Country')) ?><span>*</span></label>
                        <select id="country" class="form-control" name="country" data-validate="{required:true}" aria-required="true">
                        <option value="">Please select</option>
                        <option value="London">London</option>
                        <option value="Dubai">Dubai</option>
                        <option value="South America">South America</option>
                        <option value="Canada">Canada</option>    
                      </select>
					</div>
                  </div>
                </div>
                
              </div>
			  
			  <!--<div class="fieldset row">
                <div class="fields col-md-4">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('Street')) ?> <span>*</span></label>
                      <input name="street" id="street"  placeholder="Street" class="input-text" autocomplete="off" type="text" data-validate="{required:true}" aria-required="true">
                    </div>
                  </div>
                </div>
                <div class="fields col-md-4">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('City')) ?> <span>*</span></label>
                      <input name="city" id="city" placeholder="City" class="input-text" autocomplete="off" type="text" data-validate="{required:true}" aria-required="true">
                    </div>
                  </div>
                </div>
				<div class="fields col-md-4">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('Post Code')) ?> <span>*</span></label>
                      <input name="postcode" id="postcode" placeholder="Post Code" class="input-text" autocomplete="off" type="text" data-validate="{required:true}" aria-required="true">
                    </div>
                  </div>
                </div>
              </div>-->
              <div class="fieldset row">
                <div class="fields col-md-6">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('Company Legal Certification')) ?><span>*</span></label>
                      <input name="company_legal_certification_name" id="company_legal_certification_name" placeholder="" class="input-text" autocomplete="off" type="text" data-validate="{required:true}" aria-required="true" value="<?= $block->escapeHtmlAttr($this->helper(\InternationalEnquires\Form\Helper\Data::class)->getPostValue('company_legal_certification_name')) ?>">
                    </div>
                  </div>
                </div>
                <div class="fields col-md-6">
                  <div class="field name required">
                    <div class="control">
                      <p style="margin:0px">&nbsp;</p>
                      <input name="company_legal_certification_img" id="company_legal_certification_img" class="input-text" autocomplete="off" type="file" data-validate="{required:true}" aria-required="true" >
                    </div>
                  </div>
                </div>
              </div>
              <!--<div class="fieldset row">
                <div class="fields col-md-6">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('Password')) ?><span>*</span></label>
                     <input name="password" id="password" placeholder="Password" class="input-text" autocomplete="off" type="password"
					 data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                       data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber())?>"
                       data-validate="{required:true, 'validate-customer-password':true}"
                       autocomplete="off">
	 
					</div>
                  </div>
                </div>
                <div class="fields col-md-6">
                  <div class="field name required">
                    <div class="control">
                      <label><?= $block->escapeHtml(__('Confirm Password')) ?><span>*</span></label>
                      <input name="confirm_password" id="confirm_password" placeholder="Confirm Password" class="input-text" autocomplete="off" type="password" data-validate="{required:true,equalTo:'#password'}" >
	
                    </div>
                  </div>
                </div>
              </div>-->
              <div class="fieldset row">
                <div class="fields col-md-12">
                  <div class="primary" style="width: 100%;">
                    <button type="submit" title="Submit" class="action submit primary" style="width: 100%;"> <span>Register</span> </button>
                  </div>
                </div>
              </div>
            </fieldset>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>


